n1 = input('Digite algo:')
print('O tipo primitivo desse valor é {}'.format(type(n1)))
print('só tem espaços?', n1.isspace())
print('É um numero?', n1.isnumeric())
print('É alfabetico?', n1.isalpha())
print('É alphanumerico ?', n1.isalnum())
print('Esta em maiusculas?', n1.isupper())
print('Esta em minusculas?', n1.islower())
print('Esta capitalizado',n1.istitle())
