print('Tabela verdade - AND')
print(30 * '-')
print(True, "e", True, "=", (True and True))
print(True, "e", False, "=", (True and False))
print(False, "e", True, "=", (False and True))
print(False, "e", False, "=", (False and False))
print(30 * '-')

print('Tabela verdade - or')
print(30 * '-')
print(True, "ou", True, "=", (True or True))
print(True, "ou", False, "=", (True or False))
print(False, "ou", True, "=", (False or True))
print(False, "ou", False, "=", (False or False))
print(30 * '-')

print("Tabela Verdade - NOT")
print(30 * '-')
print("não", True, "=", not True)
print("não", False, "=", not False)
print(30 * '-')
